<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtbox_countryName</name>
   <tag></tag>
   <elementGuidId>78bbcaac-08b9-4a45-84fb-84d3635eb06e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;country&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='country']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bef4bfe1-b363-4a74-b310-826b987db719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e6d448c6-9734-4711-9b3a-517fd9136548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>75b8865b-3794-4ac8-b5dc-fb1f7a079c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>United Kingdom</value>
      <webElementGuid>b2a3e824-1a1b-449f-8a60-27d9bdc059cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]/div[@class=&quot;appointments-section&quot;]/div[@class=&quot;inner-appointment&quot;]/section[@class=&quot;edit-detail-field&quot;]/form[@class=&quot;Add-child-section&quot;]/div[@class=&quot;child-detail-inner&quot;]/div[@class=&quot;child-fields Address-field&quot;]/input[1]</value>
      <webElementGuid>4c219453-e93c-43ca-981a-6de468597807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='country']</value>
      <webElementGuid>357396ab-9f31-4214-98d1-6ea10b984215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>380d6651-0e5b-4955-8bd5-9c67074248d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'country' and @placeholder = 'United Kingdom']</value>
      <webElementGuid>3167d512-069d-41d1-ae3e-32e19d7bc3bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
