<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_cart</name>
   <tag></tag>
   <elementGuidId>a03f9da9-de0e-4219-a622-8f5b6ea4757a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ion-icon[@name='bag-handle-outline']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ion-icon[name=&quot;bag-handle-outline&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;bag handle outline&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-icon</value>
      <webElementGuid>d903b84e-b036-4a3e-bf4f-08e2c8b5fc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bag-handle-outline</value>
      <webElementGuid>3d069eb1-9e00-471d-a81d-ee6629de4011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1b5dc0f0-1b1e-46c4-8207-aed378eda3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md hydrated</value>
      <webElementGuid>fab5e3a4-6b16-423c-9d83-e9b223891dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>bag handle outline</value>
      <webElementGuid>9d638db5-59ff-4fae-9537-62fd149f3eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]/header[1]/div[@class=&quot;header-main&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;header-user-actions&quot;]/button[@class=&quot;action-btn&quot;]/a[1]/ion-icon[@class=&quot;md hydrated&quot;]</value>
      <webElementGuid>d60ca279-bbc1-4858-a726-adb2c71a5037</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ion-icon[@name='bag-handle-outline']</value>
      <webElementGuid>fde09383-eebf-46d9-8df5-1aa99eebd6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/a/ion-icon</value>
      <webElementGuid>e59158f1-c5a5-4c73-abc6-0bf4ddac1749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-icon[@name = 'bag-handle-outline']</value>
      <webElementGuid>3ff887f5-3030-416c-9372-fc464e7bad9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
