<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sidebar_category</name>
   <tag></tag>
   <elementGuidId>4d48e3c9-57ad-475c-afc6-1ad8d818a8d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Hat &amp; caps'])[1]/following::div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sidebar-category</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Category Close Clothes Add Remove Shirt shorts &amp; jeans jacket dress &amp; frock Foot&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6d7f79d-3020-42a6-ae83-a44678bc28ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar-category</value>
      <webElementGuid>33c8dd4a-581c-4285-9342-dbc311c455e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    
      Category

      
        
      
    

    
      
            
        
          
            
              

              Clothes
            

            
              
              
            
          

          
            
            
                            
                
            
                  
                  
                    
                        

                          
                            Shirt                          

                        
                      
                




                            
                
            
                  
                  
                    
                        

                          
                            shorts &amp; jeans                          

                        
                      
                




                            
                
            
                  
                  
                    
                        

                          
                            jacket                          

                        
                      
                




                            
                
            
                  
                  
                    
                        

                          
                            dress &amp; frock                          

                        
                      
                




                         
                        
            
                        
            
                        
            
            
                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Footwear
            

            
              
              
            
          

          
            
            
                         
                            
                
                  
                    
                        

                          
                            Sports                          

                        
                      
                

                            
                
                  
                    
                        

                          
                            Formal                          

                        
                      
                

                            
                
                  
                    
                        

                          
                            Casual                          

                        
                      
                

                            
                
                  
                    
                        

                          
                            Safety Shoes                          

                        
                      
                

                        
            
                        
            
                        
            
            
                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Jewelry
            

            
              
              
            
          

          
            
            
                         
                        
            
                            
                
                  
                    
                        

                          
                            Earrings                          

                        
                                        
                

                            
                
                  
                    
                        

                          
                            Couple Rings                          

                        
                                        
                

                            
                
                  
                    
                        

                          
                            Necklace                          

                        
                                        
                

                        
            
                        
            
            
                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Perfume
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                            
                
                  
                    
                        

                          
                            Clothes Perfume                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Deodorant                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            jacket                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            dress &amp; frock                          

                        
                                    
                

                        
            
            
                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Cosmetics
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                        
            
            
                            
                
                  
                    
                        

                          
                            Shampoo                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Sunscreen                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Body Wash                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Makeup Kit                          

                        
                                    
                

                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Glasses
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                        
            
            
                        
            
            
                            
                
                  
                    
                        

                          
                            Sunglasses                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Lenses                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Lenses                          

                        
                                    
                

                        
            
            
                        


          
        



            
        
          
            
              

              Bags
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                        
            
            
                        
            
            
                        
            
            
                            
                

                  
                    
                        

                          
                            Shopping Bag                          

                        
                                    
                

                            
                

                  
                    
                        

                          
                            Purse                          

                        
                                    
                

                            
                

                  
                    
                        

                          
                            Wallet                          

                        
                                    
                

                        


          
        



            
        
          
            
              

              Electronics
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                        
            
            
                        
            
            
                        
            
            
                        


          
        



            






      
    
  </value>
      <webElementGuid>a0870f1f-ad0d-4d4b-a66d-ea0a763a71f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]/main[1]/div[@class=&quot;product-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;sidebar has-scrollbar&quot;]/div[@class=&quot;sidebar-category&quot;]</value>
      <webElementGuid>88b5d09b-1e4e-489b-9532-37ef17d9052d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hat &amp; caps'])[1]/following::div[4]</value>
      <webElementGuid>3a8f64b5-7c98-45c2-a945-805ab596843c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch'])[1]/following::div[8]</value>
      <webElementGuid>346a10ab-6d2a-4d01-b99a-506535c8de81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='best sellers'])[1]/preceding::div[18]</value>
      <webElementGuid>2feb3c50-a3f9-4ac7-96de-7908b89bdc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div</value>
      <webElementGuid>f433bd09-0e15-4b96-9e47-67ee20ea6b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
    
      Category

      
        
      
    

    
      
            
        
          
            
              

              Clothes
            

            
              
              
            
          

          
            
            
                            
                
            
                  
                  
                    
                        

                          
                            Shirt                          

                        
                      
                




                            
                
            
                  
                  
                    
                        

                          
                            shorts &amp; jeans                          

                        
                      
                




                            
                
            
                  
                  
                    
                        

                          
                            jacket                          

                        
                      
                




                            
                
            
                  
                  
                    
                        

                          
                            dress &amp; frock                          

                        
                      
                




                         
                        
            
                        
            
                        
            
            
                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Footwear
            

            
              
              
            
          

          
            
            
                         
                            
                
                  
                    
                        

                          
                            Sports                          

                        
                      
                

                            
                
                  
                    
                        

                          
                            Formal                          

                        
                      
                

                            
                
                  
                    
                        

                          
                            Casual                          

                        
                      
                

                            
                
                  
                    
                        

                          
                            Safety Shoes                          

                        
                      
                

                        
            
                        
            
                        
            
            
                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Jewelry
            

            
              
              
            
          

          
            
            
                         
                        
            
                            
                
                  
                    
                        

                          
                            Earrings                          

                        
                                        
                

                            
                
                  
                    
                        

                          
                            Couple Rings                          

                        
                                        
                

                            
                
                  
                    
                        

                          
                            Necklace                          

                        
                                        
                

                        
            
                        
            
            
                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Perfume
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                            
                
                  
                    
                        

                          
                            Clothes Perfume                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Deodorant                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            jacket                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            dress &amp; frock                          

                        
                                    
                

                        
            
            
                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Cosmetics
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                        
            
            
                            
                
                  
                    
                        

                          
                            Shampoo                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Sunscreen                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Body Wash                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Makeup Kit                          

                        
                                    
                

                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Glasses
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                        
            
            
                        
            
            
                            
                
                  
                    
                        

                          
                            Sunglasses                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Lenses                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Lenses                          

                        
                                    
                

                        
            
            
                        


          
        



            
        
          
            
              

              Bags
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                        
            
            
                        
            
            
                        
            
            
                            
                

                  
                    
                        

                          
                            Shopping Bag                          

                        
                                    
                

                            
                

                  
                    
                        

                          
                            Purse                          

                        
                                    
                

                            
                

                  
                    
                        

                          
                            Wallet                          

                        
                                    
                

                        


          
        



            
        
          
            
              

              Electronics
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                        
            
            
                        
            
            
                        
            
            
                        


          
        



            






      
    
  ' or . = '
    
      Category

      
        
      
    

    
      
            
        
          
            
              

              Clothes
            

            
              
              
            
          

          
            
            
                            
                
            
                  
                  
                    
                        

                          
                            Shirt                          

                        
                      
                




                            
                
            
                  
                  
                    
                        

                          
                            shorts &amp; jeans                          

                        
                      
                




                            
                
            
                  
                  
                    
                        

                          
                            jacket                          

                        
                      
                




                            
                
            
                  
                  
                    
                        

                          
                            dress &amp; frock                          

                        
                      
                




                         
                        
            
                        
            
                        
            
            
                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Footwear
            

            
              
              
            
          

          
            
            
                         
                            
                
                  
                    
                        

                          
                            Sports                          

                        
                      
                

                            
                
                  
                    
                        

                          
                            Formal                          

                        
                      
                

                            
                
                  
                    
                        

                          
                            Casual                          

                        
                      
                

                            
                
                  
                    
                        

                          
                            Safety Shoes                          

                        
                      
                

                        
            
                        
            
                        
            
            
                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Jewelry
            

            
              
              
            
          

          
            
            
                         
                        
            
                            
                
                  
                    
                        

                          
                            Earrings                          

                        
                                        
                

                            
                
                  
                    
                        

                          
                            Couple Rings                          

                        
                                        
                

                            
                
                  
                    
                        

                          
                            Necklace                          

                        
                                        
                

                        
            
                        
            
            
                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Perfume
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                            
                
                  
                    
                        

                          
                            Clothes Perfume                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Deodorant                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            jacket                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            dress &amp; frock                          

                        
                                    
                

                        
            
            
                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Cosmetics
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                        
            
            
                            
                
                  
                    
                        

                          
                            Shampoo                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Sunscreen                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Body Wash                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Makeup Kit                          

                        
                                    
                

                        
            
            
                        
            
            
                        


          
        



            
        
          
            
              

              Glasses
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                        
            
            
                        
            
            
                            
                
                  
                    
                        

                          
                            Sunglasses                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Lenses                          

                        
                                    
                

                            
                
                  
                    
                        

                          
                            Lenses                          

                        
                                    
                

                        
            
            
                        


          
        



            
        
          
            
              

              Bags
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                        
            
            
                        
            
            
                        
            
            
                            
                

                  
                    
                        

                          
                            Shopping Bag                          

                        
                                    
                

                            
                

                  
                    
                        

                          
                            Purse                          

                        
                                    
                

                            
                

                  
                    
                        

                          
                            Wallet                          

                        
                                    
                

                        


          
        



            
        
          
            
              

              Electronics
            

            
              
              
            
          

          
            
            
                         
                        
            
                        
            
                        
            
            
                        
            
            
                        
            
            
                        


          
        



            






      
    
  ')]</value>
      <webElementGuid>7c4316c6-1d9a-490a-bfea-8d421592f07a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
