<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_available</name>
   <tag></tag>
   <elementGuidId>2fb2fc21-2534-4767-b594-bba0810ba3a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#availableCheckbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='availableCheckbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>939aec12-f511-4924-9c41-fd4dcea7573c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>0987fd81-dda1-4d32-b499-fc2daba21f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>605aff29-b200-47f1-ac75-5cbbba57683e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>available</value>
      <webElementGuid>74107222-b5c7-4ecb-8a9a-4e32e220f8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>availableCheckbox</value>
      <webElementGuid>0525cfb8-148f-488e-a1c4-f01fbf7e71c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;availableCheckbox&quot;)</value>
      <webElementGuid>f6b477d1-6300-461c-8670-0da0457abb7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='availableCheckbox']</value>
      <webElementGuid>b94475eb-f42c-4bb8-a525-ed16783b241c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>10cc46f3-585b-40bc-abd7-a77e0e0a0ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'available' and @id = 'availableCheckbox']</value>
      <webElementGuid>fab41515-555e-4a27-863f-7f618a471f2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
