<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>productName_Tshirt</name>
   <tag></tag>
   <elementGuidId>5a81bd3d-4004-4ec8-a068-80dcd633a597</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.showcase-category</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'T-Shirts')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;T-Shirts&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f3f25d5-6f9c-4ca3-a99b-a91fb891dd6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>./viewdetail.php?id=16&amp;category=</value>
      <webElementGuid>e32160db-78cc-4e3c-bb56-3269168c3c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>showcase-category</value>
      <webElementGuid>a499a75c-06b2-4c91-8127-367f67c7726e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      T-Shirts    </value>
      <webElementGuid>b1baed05-3b66-4444-9c88-9e3293c2f80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;hydrated&quot;]/body[1]/main[1]/div[@class=&quot;product-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;product-box&quot;]/div[@class=&quot;product-main&quot;]/div[@class=&quot;product-grid&quot;]/div[@class=&quot;showcase&quot;]/div[@class=&quot;showcase-content&quot;]/a[@class=&quot;showcase-category&quot;]</value>
      <webElementGuid>14aa76e0-f794-47ac-b1f2-cdc005b1f4ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'T-Shirts')]</value>
      <webElementGuid>fb2f1d58-eebc-4a98-9875-9f6c87a8181e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$25'])[1]/following::a[1]</value>
      <webElementGuid>d7649524-1adf-49b8-8abe-2786feca70a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Different color of t shirts pack of 3'])[1]/preceding::a[1]</value>
      <webElementGuid>a8eeb190-df91-4d40-8670-8b28109223c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$16'])[1]/preceding::a[2]</value>
      <webElementGuid>90ea3934-5c01-4b79-b7d6-56cecbc7f576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='T-Shirts']/parent::*</value>
      <webElementGuid>cadefc02-3a2f-43aa-88ab-f0567dc772ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, './viewdetail.php?id=16&amp;category=')]</value>
      <webElementGuid>e07935c2-bc1d-40d4-b3b1-67d0bc2f54e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/a</value>
      <webElementGuid>02e8f41c-d8f9-4cf9-8145-4cfa049913db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = './viewdetail.php?id=16&amp;category=' and (text() = '
      T-Shirts    ' or . = '
      T-Shirts    ')]</value>
      <webElementGuid>24f38c52-ab8b-413b-9bcd-2b21b3f48c6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
