<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_menu_Logout</name>
   <tag></tag>
   <elementGuidId>7daabe98-51e1-497b-a93a-9cfd94a78c45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#admin-logout-link > h6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='admin-logout-link']/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>9a9d826a-ace2-403a-8bba-042933bc8fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>9ff99f32-8962-4823-a058-af99ce3ac6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;admin-logout-link&quot;)/h6[1]</value>
      <webElementGuid>cd9041bb-7c85-4419-928e-7f36dbb0f943</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='admin-logout-link']/h6</value>
      <webElementGuid>ba958a92-67a8-465e-9570-e35cd08aee4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/following::h6[1]</value>
      <webElementGuid>fddf3512-bda8-4bea-b11d-040cda478ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::h6[2]</value>
      <webElementGuid>671ee7fc-3b49-4f06-909f-d601ad3b1a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCTS'])[1]/preceding::h6[1]</value>
      <webElementGuid>0e7bcb6d-1705-41b6-abe7-3e0b726febbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADD Products'])[1]/preceding::h6[1]</value>
      <webElementGuid>041c64a8-d24b-488e-90f9-6ee0bd0e13f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>ab9b4cef-68e5-4d60-a8e5-f16c142e1b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/h6</value>
      <webElementGuid>5cb527ac-ad2f-4b31-841d-8718548e9c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>a4a389df-6a7f-4801-af97-972d05785bda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
