<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_customerEmail</name>
   <tag></tag>
   <elementGuidId>92edf97a-b253-491d-9e78-5a6ec02afb2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='payment-form']/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ReadOnlyFormField-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>deb16653-9f7b-4f09-a689-cdf21b66883e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ReadOnlyFormField-title</value>
      <webElementGuid>9a238591-b5c2-45b1-a2e4-b4797473e843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>customer2@gmail.com</value>
      <webElementGuid>b132c3be-2adc-4c28-a9a9-27b7dfecd76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-form&quot;)/div[1]/div[1]/div[1]/div[@class=&quot;App-Global-Fields flex-container spacing-16 direction-column wrap-wrap&quot;]/div[@class=&quot;flex-item width-12&quot;]/div[@class=&quot;FormFieldGroup-container&quot;]/div[@class=&quot;ReadOnlyForm-container&quot;]/div[@class=&quot;ReadOnlyForm F-L8wL7C__EmailFormFieldGroup--readOnlyForm ReadOnlyForm--withShadow&quot;]/div[@class=&quot;ReadOnlyFormField-email ReadOnlyFormField&quot;]/div[@class=&quot;ReadOnlyFormField-container&quot;]/div[@class=&quot;ReadOnlyFormField-contentContainer&quot;]/div[@class=&quot;ReadOnlyFormField-content&quot;]/div[@class=&quot;ReadOnlyFormField-titleContainer&quot;]/div[@class=&quot;ReadOnlyFormField-title&quot;]</value>
      <webElementGuid>57916116-b4f5-48cb-a31b-a4cb3750dfdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>9c3f1aa6-9e44-4460-a236-6d24f21cb085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::div[3]</value>
      <webElementGuid>38085d9c-5c30-45f8-a8b6-d0251bbaa3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact information'])[1]/following::div[15]</value>
      <webElementGuid>77932925-3059-4884-9d4c-ea8cbe5a7804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment method'])[1]/preceding::div[2]</value>
      <webElementGuid>6fc5ea26-adc4-4c9c-b898-b0e289a16f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card'])[1]/preceding::div[6]</value>
      <webElementGuid>2a6934cb-6471-4c7b-913f-10effc623a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='customer2@gmail.com']/parent::*</value>
      <webElementGuid>bbf0a50f-54f0-48b6-b6ed-58097f9eecff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>644d86fe-b541-42e6-86ef-26d7f26fe853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'customer2@gmail.com' or . = 'customer2@gmail.com')]</value>
      <webElementGuid>fd54e932-d262-479d-8fea-268a1731407c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
