<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_items</name>
   <tag></tag>
   <elementGuidId>6a20c365-34d4-4a5f-8c51-ec6c782dc3e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/section/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.OrderDetails-items</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>05c69d33-267b-473b-aaa0-b2d47a2fa431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OrderDetails-items</value>
      <webElementGuid>35d13b29-7672-4bad-95b3-9410618431e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jacket$48.00shirt$45.00</value>
      <webElementGuid>7e877b51-e7b9-439a-a96b-7b939ece14da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App-Container local-default-background flex-container justify-content-center&quot;]/div[@class=&quot;App&quot;]/div[@class=&quot;App-Overview&quot;]/div[@class=&quot;OrderSummaryColumn&quot;]/section[@class=&quot;OrderDetails App-Overview-OrderDetails my6&quot;]/ul[@class=&quot;OrderDetails-items&quot;]</value>
      <webElementGuid>b2fd78ba-ab95-4d51-b50b-4b4ac30a6149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/section/ul</value>
      <webElementGuid>214c0269-107d-42a1-b49e-ec9e94615c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exchange rate and fees of your bank may apply'])[1]/following::ul[1]</value>
      <webElementGuid>12b8dfc9-c231-4a5b-8ae7-15499b3f1530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$93.00'])[1]/following::ul[1]</value>
      <webElementGuid>4695825f-2914-400b-9bc1-cdd5e9ea051c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>45ea518a-0250-44b3-bb45-c2d79be8ab13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'jacket$48.00shirt$45.00' or . = 'jacket$48.00shirt$45.00')]</value>
      <webElementGuid>1fac3c96-632d-4db9-b032-5fde61714398</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
