<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_InvalidCVC</name>
   <tag></tag>
   <elementGuidId>27a02576-4347-4b6a-9738-9bb98786e6e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='cardForm-fieldset']/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.FieldError-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b08244df-c713-4061-94af-5f4ff9a0715a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FieldError-container</value>
      <webElementGuid>8b6cf83a-03b2-49ba-aa0c-3ffa828ca4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your card’s security code is incomplete.</value>
      <webElementGuid>d51d0fe5-93bd-4cb0-b5fc-d4c3c3fef88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardForm-fieldset&quot;)/div[@class=&quot;FormFieldGroup-container&quot;]/div[@class=&quot;FieldError-container&quot;]</value>
      <webElementGuid>6d59b7ac-c663-457e-9839-469b11a3def1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='cardForm-fieldset']/div/div[4]</value>
      <webElementGuid>c7428b58-559d-4de1-8f34-7287e5873154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card information'])[1]/following::div[18]</value>
      <webElementGuid>9d1e49ba-478b-403d-a735-f2906a986a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card'])[1]/following::div[28]</value>
      <webElementGuid>69a1a449-c49f-47a6-9a2e-1818f5ecbb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cardholder name'])[1]/preceding::div[4]</value>
      <webElementGuid>e0ce7bd4-5c92-4186-a698-ca7e0d1bd268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[4]</value>
      <webElementGuid>99b24647-cb3d-489b-ab3d-6a37c7525249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your card’s security code is incomplete.' or . = 'Your card’s security code is incomplete.')]</value>
      <webElementGuid>72cd46e3-e654-4519-8e7a-8c90a88215cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
