<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_InvalidCardNumber</name>
   <tag></tag>
   <elementGuidId>18fe9ec3-a10a-47be-9ca0-5aeac650fa7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='cardForm-fieldset']/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.FieldError-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>27d72fc0-fba9-4c64-b655-94a6543680f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FieldError-container</value>
      <webElementGuid>5636614a-13f6-48fb-a091-d13351e96b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your card number is invalid.</value>
      <webElementGuid>cbbd9719-a0fc-450a-8b4b-8bcc1d0f130e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardForm-fieldset&quot;)/div[@class=&quot;FormFieldGroup-container&quot;]/div[@class=&quot;FieldError-container&quot;]</value>
      <webElementGuid>009f9b2b-0f13-487e-8d1f-468d21860133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='cardForm-fieldset']/div/div[4]</value>
      <webElementGuid>960e4ee8-f999-47c5-827f-710bac1ca5dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card information'])[1]/following::div[14]</value>
      <webElementGuid>5a3ccd42-ec2f-432b-a6d1-8889c37e6ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card'])[1]/following::div[24]</value>
      <webElementGuid>5cad1fdc-3fd8-4288-8f90-cfeb86365f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cardholder name'])[1]/preceding::div[4]</value>
      <webElementGuid>360ebf51-4a2a-4111-b29f-c56ce9cd510f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[4]</value>
      <webElementGuid>7cee1707-8a29-47b2-aa60-a8774c50432b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your card number is invalid.' or . = 'Your card number is invalid.')]</value>
      <webElementGuid>41b39604-5777-4ec3-a182-fdfbcb7eb264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
