<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_CardDeclined</name>
   <tag></tag>
   <elementGuidId>1271ca8c-7b99-4028-9d7d-1c1c41359717</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='cardForm-fieldset']/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.FieldError-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a62caab-9a2f-498c-8b84-512e9b7488f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FieldError-container</value>
      <webElementGuid>5ef33c8f-d37e-4027-b9e6-558cc1ba54d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your credit card was declined. Try paying with a debit card instead.</value>
      <webElementGuid>00861b48-e0e2-4539-8d07-29c5afc672c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardForm-fieldset&quot;)/div[@class=&quot;FormFieldGroup-container&quot;]/div[@class=&quot;FieldError-container&quot;]</value>
      <webElementGuid>296fe686-c42c-4daa-b19e-797d9de32e05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='cardForm-fieldset']/div/div[4]</value>
      <webElementGuid>831fad5e-35c2-49c2-afc4-90a4bbff23d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card information'])[1]/following::div[14]</value>
      <webElementGuid>f2e2afbe-06c9-462a-9a4d-3e265b9bf8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card'])[1]/following::div[24]</value>
      <webElementGuid>ff12b15f-e2a1-42d5-98f4-e486bdf64dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cardholder name'])[1]/preceding::div[4]</value>
      <webElementGuid>db13767f-3b26-49f2-a3cc-6d3397cc0fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[4]</value>
      <webElementGuid>a5954827-eb51-4463-958f-b60b83efe372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your credit card was declined. Try paying with a debit card instead.' or . = 'Your credit card was declined. Try paying with a debit card instead.')]</value>
      <webElementGuid>fc8ca8db-1639-4535-bf25-548257353127</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
