<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_NetworkInterrupted</name>
   <tag></tag>
   <elementGuidId>dab4a599-2df2-4318-bcc0-b2807290f4c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.FullPageMessage-Message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56a6e34f-a0a9-44da-9c87-ae9702e97233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FullPageMessage-Message</value>
      <webElementGuid>12a79983-31b4-45fc-882d-0ca247c680b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You’re all done hereYou’ve either completed your payment or this checkout session has timed out.</value>
      <webElementGuid>a7dfc250-17d0-4722-b732-cb415b8c8c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;FullPageMessage&quot;]/div[1]/div[@class=&quot;FullPageMessage-Message&quot;]</value>
      <webElementGuid>dbd80f60-57e5-44eb-b21a-ef013999b079</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div</value>
      <webElementGuid>74227902-12cd-4816-9d1b-4485d91f219a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>41911a0b-35fc-483d-955d-1de74350de5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'You’re all done hereYou’ve either completed your payment or this checkout session has timed out.' or . = 'You’re all done hereYou’ve either completed your payment or this checkout session has timed out.')]</value>
      <webElementGuid>8e0bf90e-3203-4251-b915-81fad4a65f1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
