<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_ExpiredCard</name>
   <tag></tag>
   <elementGuidId>bd605400-63c5-4e50-bca6-7e68458aff34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='cardForm-fieldset']/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.FieldError-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5ba8e2e-334d-4229-b122-7919c8103c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>FieldError-container</value>
      <webElementGuid>f1788575-6226-4646-bb82-c615807f9f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your card’s expiration year is in the past.</value>
      <webElementGuid>f1403968-d0fc-4a32-b17e-d33a73e0ea7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardForm-fieldset&quot;)/div[@class=&quot;FormFieldGroup-container&quot;]/div[@class=&quot;FieldError-container&quot;]</value>
      <webElementGuid>b6939e9d-7804-4d85-b06a-dbc541700e8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='cardForm-fieldset']/div/div[4]</value>
      <webElementGuid>adb6009a-cd7f-489a-802c-332df749f1bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card information'])[1]/following::div[20]</value>
      <webElementGuid>95bdd1f5-c25c-4a18-80e5-43f987c89a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card'])[1]/following::div[30]</value>
      <webElementGuid>a5fdfaa8-dc07-4e67-a8f5-7c925236ddc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cardholder name'])[1]/preceding::div[4]</value>
      <webElementGuid>642961a7-314f-4ab0-aad3-5850371f570a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[4]</value>
      <webElementGuid>ccaaf150-aca2-4672-bd40-452a4d71bb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your card’s expiration year is in the past.' or . = 'Your card’s expiration year is in the past.')]</value>
      <webElementGuid>df284c3b-1176-4c43-aa1e-869b2b93c254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
