<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_Required_cardInformation</name>
   <tag></tag>
   <elementGuidId>e1bba3bb-fccc-4176-98e4-928925ff50b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='required-cardNumber-[&quot;visa&quot;,&quot;mastercard&quot;,&quot;amex&quot;,&quot;jcb&quot;,&quot;discover&quot;,&quot;diners&quot;]-fieldset']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fc5f7cce-e54b-4f50-8577-a5dd841db9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>8c2aa0e0-2466-4e3c-ba03-e9306f1c142f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>required-cardNumber-[&quot;visa&quot;,&quot;mastercard&quot;,&quot;amex&quot;,&quot;jcb&quot;,&quot;discover&quot;,&quot;diners&quot;]-fieldset</value>
      <webElementGuid>89b689c9-8c3b-4b49-9d82-c9e312211336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>EmptyFieldError</value>
      <webElementGuid>1fb2b01f-a0f9-4898-a249-753a17ff6b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>f85d7b18-c2e7-4254-8d21-f16a18ab24c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;required-cardNumber-[&quot;visa&quot;,&quot;mastercard&quot;,&quot;amex&quot;,&quot;jcb&quot;,&quot;discover&quot;,&quot;diners&quot;]-fieldset&quot;)</value>
      <webElementGuid>0cf95814-e26e-4d34-8aba-d7b8a504abc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='required-cardNumber-[&quot;visa&quot;,&quot;mastercard&quot;,&quot;amex&quot;,&quot;jcb&quot;,&quot;discover&quot;,&quot;diners&quot;]-fieldset']</value>
      <webElementGuid>f657ad4a-c5cb-4647-9914-ab3830a2a43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/div/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/span/span</value>
      <webElementGuid>a38470e9-88c8-4ce9-b006-c17a521fdaee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card information'])[1]/following::span[2]</value>
      <webElementGuid>c47c4384-21a3-450b-86d3-c3f01972a99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card'])[1]/following::span[3]</value>
      <webElementGuid>983f06d4-9bea-42c4-8ecf-29931487ed0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cardholder name'])[1]/preceding::span[8]</value>
      <webElementGuid>12f5929c-7386-4dcd-9694-95e822e29682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[2]/preceding::span[9]</value>
      <webElementGuid>dd386466-a67c-4e4c-bfc3-15ad233ea697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Required']/parent::*</value>
      <webElementGuid>6f0d9254-e0f8-44da-bd8d-381ee66b1b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/span/span</value>
      <webElementGuid>f775b32a-91ad-4dd2-b277-b83a266c54af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'required-cardNumber-[&quot;visa&quot;,&quot;mastercard&quot;,&quot;amex&quot;,&quot;jcb&quot;,&quot;discover&quot;,&quot;diners&quot;]-fieldset' and (text() = 'Required' or . = 'Required')]</value>
      <webElementGuid>acf8d320-8586-452e-b017-d3da7529d77e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
