<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_Required_CardholderName</name>
   <tag></tag>
   <elementGuidId>2e8748f3-edb9-485d-b574-ce09c70b8d63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='required-billingName-fieldset']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#required-billingName-fieldset</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>db597994-ff65-441c-b5ff-fe887f1c3799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>24a3f7d3-b8bc-4899-acf5-29c11fa2f70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>required-billingName-fieldset</value>
      <webElementGuid>cd98aef4-00db-4455-97d7-4655c0c50145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>EmptyFieldError</value>
      <webElementGuid>6dfc7d25-9043-484f-b2f7-ec222bdf6d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Required</value>
      <webElementGuid>3f10416c-3431-4e9f-bdd3-f3d057b52c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;required-billingName-fieldset&quot;)</value>
      <webElementGuid>bda8adcb-2d9d-4fa6-8385-fbce71c41c9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='required-billingName-fieldset']</value>
      <webElementGuid>b61d0a27-a7f4-4a73-8052-ec53fc2b362b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='payment-form']/div/div/div/div[2]/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/span/span</value>
      <webElementGuid>99294a38-2d07-417a-bf44-e950826a74e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cardholder name'])[1]/following::span[2]</value>
      <webElementGuid>b4dfedc1-7828-4302-b53d-24f27bb9dd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[1]/following::span[10]</value>
      <webElementGuid>41add558-292a-428c-82dc-87841b8c13a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country or region'])[1]/preceding::span[6]</value>
      <webElementGuid>0cc74d54-45c5-48d0-9858-4d0e83718efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save my information for faster checkout'])[1]/preceding::span[12]</value>
      <webElementGuid>65c661dd-04ac-4989-957e-59f0d85028ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div/div/div/div/span/span</value>
      <webElementGuid>841d2255-6a30-4120-a625-a081b31253bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'required-billingName-fieldset' and (text() = 'Required' or . = 'Required')]</value>
      <webElementGuid>20bbe6a8-f82f-4687-89f4-d0fde5128a83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
