<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>name_item1</name>
   <tag></tag>
   <elementGuidId>81636b3a-40a9-48f5-bcf1-687a7a6e3944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/section/ul/li/div/div/div[3]/span/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ExpandableText--truncated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8df2e66b-6503-4c4d-aeb7-446c2d56246a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ExpandableText--truncated</value>
      <webElementGuid>5a5c323d-79eb-4ef0-86c5-adec7c5551c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>jacket</value>
      <webElementGuid>d50902e9-c7c5-440e-ab81-611a0a0ff6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App-Container local-default-background flex-container justify-content-center&quot;]/div[@class=&quot;App&quot;]/div[@class=&quot;App-Overview&quot;]/div[@class=&quot;OrderSummaryColumn&quot;]/section[@class=&quot;OrderDetails App-Overview-OrderDetails my6&quot;]/ul[@class=&quot;OrderDetails-items&quot;]/li[@class=&quot;OrderDetails-item&quot;]/div[@class=&quot;LineItem flex-container align-items-flex-start&quot;]/div[@class=&quot;flex-container justify-content-space-between align-items-baseline wrap-wrap width-grow&quot;]/div[@class=&quot;LineItem-productName flex-item width-auto&quot;]/span[@class=&quot;Text Text-color--default Text-fontSize--14 Text-fontWeight--500&quot;]/div[@class=&quot;ExpandableText&quot;]/div[@class=&quot;ExpandableText--truncated&quot;]</value>
      <webElementGuid>57b2d10e-0378-45c0-b529-3fc45e803292</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/section/ul/li/div/div/div[3]/span/div/div</value>
      <webElementGuid>b54f9257-847d-4198-9c05-d785ad0f9b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exchange rate and fees of your bank may apply'])[1]/following::div[8]</value>
      <webElementGuid>5bcc23dc-affe-4b13-b1b6-4fc655904ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$93.00'])[1]/following::div[9]</value>
      <webElementGuid>9d678d2d-1b28-4d35-be3c-8a9c5b21344f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$48.00'])[1]/preceding::div[8]</value>
      <webElementGuid>1011b7b8-f4bd-425b-abe6-396fd391ce08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shirt'])[1]/preceding::div[12]</value>
      <webElementGuid>bee9fa43-d123-4bfa-a169-24ccfbfb42b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='jacket']/parent::*</value>
      <webElementGuid>4ef1977e-4d05-4da3-bae2-da6844f985de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div</value>
      <webElementGuid>ef862973-5d1b-4be6-91da-0e5ff58ea99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'jacket' or . = 'jacket')]</value>
      <webElementGuid>9e59a04f-bcb2-4ac9-948e-5950fdd70180</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
