<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>name_item2</name>
   <tag></tag>
   <elementGuidId>e7c990c3-eacd-4b91-b277-78bb31b62558</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/section/ul/li[2]/div/div/div[3]/span/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>223366df-8ab4-4674-9fcd-24134dc73431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ExpandableText--truncated</value>
      <webElementGuid>b47fd28e-7227-4ec8-9216-a3de506173e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>shirt</value>
      <webElementGuid>d3189a2d-fe3c-403e-8912-11667c1d74b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App-Container local-default-background flex-container justify-content-center&quot;]/div[@class=&quot;App&quot;]/div[@class=&quot;App-Overview&quot;]/div[@class=&quot;OrderSummaryColumn&quot;]/section[@class=&quot;OrderDetails App-Overview-OrderDetails my6&quot;]/ul[@class=&quot;OrderDetails-items&quot;]/li[@class=&quot;OrderDetails-item&quot;]/div[@class=&quot;LineItem flex-container align-items-flex-start&quot;]/div[@class=&quot;flex-container justify-content-space-between align-items-baseline wrap-wrap width-grow&quot;]/div[@class=&quot;LineItem-productName flex-item width-auto&quot;]/span[@class=&quot;Text Text-color--default Text-fontSize--14 Text-fontWeight--500&quot;]/div[@class=&quot;ExpandableText&quot;]/div[@class=&quot;ExpandableText--truncated&quot;]</value>
      <webElementGuid>30bb4aa6-2423-49a3-aebc-d1b2a74a9d0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/section/ul/li[2]/div/div/div[3]/span/div/div</value>
      <webElementGuid>11698861-db25-495d-b5ab-5c72bd3a532b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$48.00'])[1]/following::div[7]</value>
      <webElementGuid>cf624b8c-122b-44a4-920b-a27017905cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jacket'])[1]/following::div[16]</value>
      <webElementGuid>d2c429d9-befa-4326-907a-acfb41feb0a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$45.00'])[1]/preceding::div[8]</value>
      <webElementGuid>9c308b7c-92b4-49ef-a003-408d7d8798ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or'])[1]/preceding::div[16]</value>
      <webElementGuid>6da2bdf9-62ba-49b8-a258-4f92930a937f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='shirt']/parent::*</value>
      <webElementGuid>da206ada-4777-4943-b1f5-69a27826e590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[3]/span/div/div</value>
      <webElementGuid>52ec1176-7cc6-4f84-b8ec-c5fd710fe9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'shirt' or . = 'shirt')]</value>
      <webElementGuid>fcfca7f7-df87-4a9c-b0f8-b42f12cab678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
