<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>price_item2</name>
   <tag></tag>
   <elementGuidId>fb0253c5-56ad-4281-a844-2af804e57833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/section/ul/li[2]/div/div/div[6]/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ddf45cb-6c32-45e1-951a-39588e32c099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CurrencyAmount</value>
      <webElementGuid>f9404424-6eab-4be8-be2a-90545779b628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$45.00</value>
      <webElementGuid>de6f6141-59c3-4407-9d04-df27a2d91dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App-Container local-default-background flex-container justify-content-center&quot;]/div[@class=&quot;App&quot;]/div[@class=&quot;App-Overview&quot;]/div[@class=&quot;OrderSummaryColumn&quot;]/section[@class=&quot;OrderDetails App-Overview-OrderDetails my6&quot;]/ul[@class=&quot;OrderDetails-items&quot;]/li[@class=&quot;OrderDetails-item&quot;]/div[@class=&quot;LineItem flex-container align-items-flex-start&quot;]/div[@class=&quot;flex-container justify-content-space-between align-items-baseline wrap-wrap width-grow&quot;]/div[@class=&quot;flex-container Placeholder&quot;]/div[@class=&quot;ml2 flex-item width-fixed&quot;]/span[@class=&quot;Text Text-color--default Text-fontSize--14 Text-fontWeight--500 Text--tabularNumbers&quot;]/span[@class=&quot;CurrencyAmount&quot;]</value>
      <webElementGuid>55155221-f005-4bcd-9fc0-ffa201072eba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/section/ul/li[2]/div/div/div[6]/div/span/span</value>
      <webElementGuid>b6e7dc01-909e-4704-8313-150e6875b8fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shirt'])[1]/following::span[3]</value>
      <webElementGuid>3d2da8a5-a670-43ca-baaa-7e8097ae1348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$48.00'])[1]/following::span[4]</value>
      <webElementGuid>0d9dd837-2089-49d9-b022-12c706e6df24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or'])[1]/preceding::span[1]</value>
      <webElementGuid>daef4541-ab27-40c0-a465-cc62322ba0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact information'])[1]/preceding::span[2]</value>
      <webElementGuid>77d94d18-2628-48b9-bebd-fe69d227ff66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$45.00']/parent::*</value>
      <webElementGuid>a796394f-c301-401c-b10f-e179403c3252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[6]/div/span/span</value>
      <webElementGuid>638bde0a-80a5-4374-808a-34637353cfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$45.00' or . = '$45.00')]</value>
      <webElementGuid>ea0e8efb-18fc-400a-94df-67e79af637cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
