<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtbox_cardCvc</name>
   <tag></tag>
   <elementGuidId>7ff341df-2922-4c83-aabd-17cd14fdc633</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardCvc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cardCvc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6efc785-cb22-4c15-b388-e3543433503e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CheckoutInput CheckoutInput--tabularnums Input Input--empty</value>
      <webElementGuid>53cbc949-98ce-405b-a0f1-c954d4cf09a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>cc-csc</value>
      <webElementGuid>4f28c0cc-1200-48cc-b95d-d041cd8e2532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>443251e3-79ce-4f0f-982e-ada68f726311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ea3c47d8-8e6d-493a-9e3b-5f68fa03c8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardCvc</value>
      <webElementGuid>adbf4091-5622-417b-a548-9596a4ebc99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardCvc</value>
      <webElementGuid>46453138-d670-4f34-9506-f5321d031403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce9cee64-0346-4e47-8e09-25c275742ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>835f3ba0-c6eb-4d91-ae33-ec058021749d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>CVC</value>
      <webElementGuid>6a43fc9f-0c07-48b6-b97c-989c3a9d9d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CVC</value>
      <webElementGuid>7cfbcdad-6ab8-4dce-8403-3730e2284672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6739424f-83c9-4b97-b9ef-4ad0499b3629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-1p-ignore</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2283d0b-07d2-411b-b4c8-8bff5d996232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lp-ignore</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2def0a91-03df-4725-ad6c-6ff89fae21e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardCvc&quot;)</value>
      <webElementGuid>c47528cb-e8e8-4587-837e-78a88c8cdfe5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardCvc']</value>
      <webElementGuid>0f618738-82bc-4ce9-a914-5935b28b7514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='cardForm-fieldset']/div/div[3]/div/div/span/input</value>
      <webElementGuid>d0724eef-233b-49dc-b019-492836500acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/input</value>
      <webElementGuid>60bf6466-dfe5-431d-b3d5-8202e6c6de00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cardCvc' and @name = 'cardCvc' and @type = 'text' and @placeholder = 'CVC']</value>
      <webElementGuid>cc8dce47-1fe1-4e95-be4d-4fce6a8190f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
