<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_logout</name>
   <tag></tag>
   <elementGuidId>1fd3a9ef-e070-4766-afb9-a34083a64396</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ion-icon[name=&quot;log-out-outline&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ion-icon[@name='log-out-outline']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ion-icon</value>
      <webElementGuid>5d9b714a-e498-4507-b504-ed1dcb1bcead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>log-out-outline</value>
      <webElementGuid>512b23fd-b382-4bbc-8aa9-115e2316dd50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8ba6f4aa-7f54-40a7-bdc8-2324ecb8261c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md hydrated</value>
      <webElementGuid>63b7c9b2-6f80-44d7-8a6b-e762eb8e2fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>log out outline</value>
      <webElementGuid>c0b65dd1-c4f6-45e6-8190-e4f1e119c766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logout-link&quot;)/ion-icon[@class=&quot;md hydrated&quot;]</value>
      <webElementGuid>6dd05bc0-05f7-4203-8044-c6f23708fcfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ion-icon[@name='log-out-outline']</value>
      <webElementGuid>6a818f95-20e4-48ca-8230-fc0fb1528f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='logout-link']/ion-icon</value>
      <webElementGuid>c52f96a1-0d55-4eed-b433-310b48772527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/a/ion-icon</value>
      <webElementGuid>efe1bbb9-26ed-4f7a-8bf0-3127020b3d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ion-icon[@name = 'log-out-outline']</value>
      <webElementGuid>6ec4e20a-c527-4e34-82e3-7a2955ae6147</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
