<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Available</name>
   <tag></tag>
   <elementGuidId>3facbc53-a0a5-4629-b4a9-cc6638016b48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.form-check-label</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '
          Available
        ' or . = '
          Available
        ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>967edd58-a143-4e55-a718-9d1231eb065a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
      <webElementGuid>e9cb238d-5f90-43e8-a5d1-f05d289a14a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>flexRadioDefault2</value>
      <webElementGuid>b93b8a6d-137a-49f5-91ea-c623a4bbdde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Available
        </value>
      <webElementGuid>1ab10141-62b6-4ec5-a93d-c4341d45be83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7cd75bd42576af392dc489da36eafdeb</value>
      <webElementGuid>cd098b00-7b89-4303-8179-597c26b1ec4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      <webElementGuid>ae344901-e336-4684-81da-6fa1b77f4bd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-check-label ')]</value>
      <webElementGuid>b7a2a7cd-9224-43f0-bda0-d70fd73f7e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '
          Available
        ' or . = '
          Available
        ')]</value>
      <webElementGuid>0b5d7be5-c46f-4b0e-9cdd-7dc7de296154</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
