<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_whiteShirt</name>
   <tag></tag>
   <elementGuidId>aab30039-77d4-4832-84c6-24a96194595c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.sFlh5c.FyHeAf.iPVvYb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0ef6509e-b484-4c58-a4c7-a484a1395003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.houseofblanks.com/cdn/shop/files/HeavyweightTshirt_White_02_1.jpg?v=1726516823&amp;width=1946</value>
      <webElementGuid>f7aca4fd-0d8d-43a3-bbee-caefda30b187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sFlh5c FyHeAf iPVvYb</value>
      <webElementGuid>0850da44-8382-4fcd-980d-d30c4c3cf0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Blank Heavyweight T-shirt White 275 GSM – House Of Blanks</value>
      <webElementGuid>1d04125c-cf88-43d1-8c64-aaf11352e90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>kn3ccd</value>
      <webElementGuid>796ff305-31bb-4958-bc7d-a0805a49f081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;osuid_0&quot;)/div[@class=&quot;HV5Yde&quot;]/div[@class=&quot;Fp3I9&quot;]/div[@class=&quot;hwRvZe&quot;]/div[1]/div[@class=&quot;Z7HyUd&quot;]/c-wiz[1]/div[@class=&quot;hh1Ztf ip4nvd&quot;]/div[@class=&quot;cLqwWc&quot;]/div[@class=&quot;v6bUne&quot;]/div[@class=&quot;p7sI2 PUxBg&quot;]/a[@class=&quot;YsLeY&quot;]/img[@class=&quot;sFlh5c FyHeAf iPVvYb&quot;]</value>
      <webElementGuid>ae8310de-6443-4cc9-b148-fd992a393ccb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='osuid_0']/div[3]/div[2]/div/div/div/c-wiz/div/div/div[2]/div/a/img</value>
      <webElementGuid>73327817-38c7-4cea-b360-00cb956fa831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Blank Heavyweight T-shirt White 275 GSM – House Of Blanks'])[2]</value>
      <webElementGuid>76323e68-143e-45fa-a06d-9e04ea831ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/c-wiz/div/div/div[2]/div/a/img</value>
      <webElementGuid>49924366-c8ee-41c7-b5af-af265f020d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.houseofblanks.com/cdn/shop/files/HeavyweightTshirt_White_02_1.jpg?v=1726516823&amp;width=1946' and @alt = 'Blank Heavyweight T-shirt White 275 GSM – House Of Blanks']</value>
      <webElementGuid>0a98cb76-c05d-4fd3-8d3e-a7ef805d3200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
