<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tick_available</name>
   <tag></tag>
   <elementGuidId>746888b8-cbaf-4fdd-ac9a-c3133d66167a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flexRadioDefault2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='flexRadioDefault2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80150760-6e32-483f-9668-ddd47ea93d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>334fa730-d584-4026-bc09-bb07d44679f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>31deb68d-ac2e-45a2-8b79-a48a551ee25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>flexRadioDefault</value>
      <webElementGuid>b02ba57c-24f7-4826-9269-9aaddbaa111a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flexRadioDefault2</value>
      <webElementGuid>1404e822-697b-47f7-87eb-eaeba357c151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flexRadioDefault2&quot;)</value>
      <webElementGuid>5ba9a97d-35dc-4a66-bb7c-17b3f58540b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='flexRadioDefault2']</value>
      <webElementGuid>b6d66465-7fb4-4e1c-8c2c-1eef67785ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>72b3009f-14e5-4859-ba41-8e652572db7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'flexRadioDefault' and @id = 'flexRadioDefault2']</value>
      <webElementGuid>b57f5d4f-2fcc-4361-b74d-2413f0c63627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
