<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_product_name</name>
   <tag></tag>
   <elementGuidId>875bca01-940d-4c91-8026-ac06d4d94812</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;prod-title&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='prod-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>399002b4-a4ed-42aa-a43d-34625f2a056b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prod-title</value>
      <webElementGuid>78428fab-fbce-44a5-bc20-4d2fcb694560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c26730cb-2492-4dc3-a941-8625b4c2661c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9d12da96-f02c-4136-b36f-117481b304d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Product Name...</value>
      <webElementGuid>88424f78-3ff6-4e54-94d3-f9c452540739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e4266c64-e05e-4a82-854e-6e1c4e8c4657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;content-box-post&quot;]/div[@class=&quot;addpost&quot;]/form[@class=&quot;row g-3&quot;]/div[@class=&quot;col-12&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>c1e142ea-d822-4559-a4a0-6c77d4de42e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='prod-title']</value>
      <webElementGuid>e9c1cebf-77fd-4745-a546-c62cf60429bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>90542138-8344-4e15-9b41-f4c930cae0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'prod-title' and @type = 'text' and @placeholder = 'Product Name...']</value>
      <webElementGuid>12b6a6f5-35d8-41fc-ba37-aec3b0f88f85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
