<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_website_logo_current</name>
   <tag></tag>
   <elementGuidId>9ce2b97b-714b-4adf-93f8-dfe54d897d07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2ad001d9-8125-4d3b-975d-2b8f67f6fb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>upload/brand.png</value>
      <webElementGuid>9d3a190f-d585-4d2a-9976-0b40b63ce542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;content-box&quot;]/div[@class=&quot;settings&quot;]/form[@class=&quot;row g-3&quot;]/div[@class=&quot;col-12&quot;]/img[1]</value>
      <webElementGuid>4db293ee-eaef-401b-8dab-269560724969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>7528a053-7817-4723-9bca-0c1129a33690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'upload/brand.png']</value>
      <webElementGuid>d71521b7-fcf8-463f-b6ab-c25c4555634c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
