<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>new_website_logo</name>
   <tag></tag>
   <elementGuidId>bc0a819c-84ff-4386-9850-80147e7da780</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.sFlh5c.FyHeAf.iPVvYb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d7fe80c3-3d5d-4950-924e-1ddb7810d100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://img.freepik.com/free-vector/www-internet-globe-grid_78370-2008.jpg?semt=ais_hybrid&amp;w=740&amp;q=80</value>
      <webElementGuid>2d34d71a-7194-4b3f-af09-f556c971cffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sFlh5c FyHeAf iPVvYb</value>
      <webElementGuid>56ef57ec-8819-4c53-a6f8-ff01208c1879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Website logo jpg Images - Free Download on Freepik</value>
      <webElementGuid>2476f1af-3522-4752-8295-5b212253d6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>kn3ccd</value>
      <webElementGuid>c6e495ec-d12c-4476-8c07-27591cc1555a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;osuid_0&quot;)/div[@class=&quot;HV5Yde&quot;]/div[@class=&quot;Fp3I9&quot;]/div[@class=&quot;hwRvZe&quot;]/div[1]/div[@class=&quot;Z7HyUd&quot;]/c-wiz[1]/div[@class=&quot;hh1Ztf ip4nvd&quot;]/div[@class=&quot;cLqwWc&quot;]/div[@class=&quot;v6bUne&quot;]/div[@class=&quot;p7sI2 PUxBg&quot;]/a[@class=&quot;YsLeY&quot;]/img[@class=&quot;sFlh5c FyHeAf iPVvYb&quot;]</value>
      <webElementGuid>23c829b2-6ec0-4714-b317-242ba031a40d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='osuid_0']/div[3]/div[2]/div/div/div/c-wiz/div/div/div[2]/div/a/img</value>
      <webElementGuid>73780bd6-8cae-4cee-b102-31945c52d423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Website logo jpg Images - Free Download on Freepik'])[2]</value>
      <webElementGuid>cb20382f-92e6-4c59-9286-eca325872c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/c-wiz/div/div/div[2]/div/a/img</value>
      <webElementGuid>f1356df2-8b38-4715-b086-08bddc662424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://img.freepik.com/free-vector/www-internet-globe-grid_78370-2008.jpg?semt=ais_hybrid&amp;w=740&amp;q=80' and @alt = 'Website logo jpg Images - Free Download on Freepik']</value>
      <webElementGuid>95a5709a-755a-4b69-843d-461a51f96495</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
