<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtview_userEmail</name>
   <tag></tag>
   <elementGuidId>1b3db8fb-71f0-44df-8ac2-c0bfbbcf7d80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='orderDetailsBody']/p[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(5)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>8910489c-4d4c-4ffd-afab-a94cb40eb0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email: customer2@gmail.com</value>
      <webElementGuid>6857033a-ff06-4f67-b906-93911be4ddd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderDetailsBody&quot;)/p[5]</value>
      <webElementGuid>d0ed9e11-0f48-4098-a0b5-2dbe1525ceac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderDetailsBody']/p[5]</value>
      <webElementGuid>66922415-cb6f-47de-9947-84011493d953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone:'])[1]/following::p[1]</value>
      <webElementGuid>3c81caf7-3414-49c0-a817-a0b45c62f75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address:'])[1]/following::p[2]</value>
      <webElementGuid>e76eb2dd-90d2-49c1-920c-b2d18c346c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date:'])[1]/preceding::p[1]</value>
      <webElementGuid>dda7fdaa-9bae-48dd-b915-6707d7367f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]</value>
      <webElementGuid>3cc9c7c4-c06f-4cd5-a02f-1238005c9b06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Email: customer2@gmail.com' or . = 'Email: customer2@gmail.com')]</value>
      <webElementGuid>ea9f4a52-518e-4572-a0a1-80ceb5f74493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
