<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtview_date_time_order</name>
   <tag></tag>
   <elementGuidId>deaedb65-a177-4e0d-86fd-9e9e3f8a17d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='orderDetailsBody']/p[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(6)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ebb6a62a-66fe-4f81-955e-6a9c3724e8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Date: 2026-05-16 11:50</value>
      <webElementGuid>5b540522-fcb7-400a-b31f-c69166004fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderDetailsBody&quot;)/p[6]</value>
      <webElementGuid>4669799e-25f1-48c4-8333-489f3c5a322c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderDetailsBody']/p[6]</value>
      <webElementGuid>a3a1d36f-affc-44f3-a2a6-58312a5ade0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email:'])[1]/following::p[1]</value>
      <webElementGuid>16ffae4b-260e-4cf8-af55-e444554a1712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone:'])[1]/following::p[2]</value>
      <webElementGuid>8e8efc02-20d5-4539-b2da-c87a16be0714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items:'])[1]/preceding::p[1]</value>
      <webElementGuid>f3e7e147-6123-4098-9499-8906cb5022e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]</value>
      <webElementGuid>263df74a-275e-48bb-8b88-231d6f221aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Date: 2026-05-16 11:50' or . = 'Date: 2026-05-16 11:50')]</value>
      <webElementGuid>93b19b6c-3bbf-484a-ad13-20864bb7b640</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
