<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtview_userAddress</name>
   <tag></tag>
   <elementGuidId>1436a6db-115d-4c22-abf3-bf2cba9d7fa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='orderDetailsBody']/p[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>fd793d02-25a3-40e4-ac75-5b5a5b47711f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Address: Customer Test, 03, Quang Trung, Da Nang, 55000, Vietnam</value>
      <webElementGuid>2d5d3fcc-c9d0-4e8b-97ef-c9a1da68bb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;orderDetailsBody&quot;)/p[3]</value>
      <webElementGuid>1fc2b94d-e474-40c5-99bf-2e85df776169</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='orderDetailsBody']/p[3]</value>
      <webElementGuid>14664096-8166-4477-9719-8fc957e0787a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status:'])[1]/following::p[1]</value>
      <webElementGuid>5b333b25-6c0a-4992-9361-f564b5d70c7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/following::p[2]</value>
      <webElementGuid>7ddb632c-6ab0-49d0-806c-2a50010ea19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone:'])[1]/preceding::p[1]</value>
      <webElementGuid>de98490d-0563-4dbd-8447-f181d86a1980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer Test, 03, Quang Trung, Da Nang, 55000, Vietnam']/parent::*</value>
      <webElementGuid>b8e6d1d1-60d1-46e9-880d-4f1d2a6f2b24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]</value>
      <webElementGuid>aadef5dd-1b7f-4764-9aff-0018dbe696d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Address: Customer Test, 03, Quang Trung, Da Nang, 55000, Vietnam' or . = 'Address: Customer Test, 03, Quang Trung, Da Nang, 55000, Vietnam')]</value>
      <webElementGuid>d151974e-1b02-4ab4-972e-c4199cf55217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
